name: Build & Deploy Angular to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build Angular
        run: npx ng build --configuration=production --base-href "/AmesaBase/"

      # 🔎 Resolve the actual dist folder from angular.json
      - name: Resolve dist path
        id: dist
        run: |
          node -e "const p=require('./angular.json'); const proj=Object.values(p.projects)[0]; const t=(proj.targets||proj.architect); const out=t.build.options.outputPath; console.log(out)" > distpath.txt
          echo "DIST_DIR=$(cat distpath.txt)" >> $GITHUB_ENV
          echo "Resolved DIST_DIR=$DIST_DIR"
          ls -la "$DIST_DIR"

      # 🚫 Disable Jekyll in the right folder (harmless if not using Jekyll)
      - name: Add .nojekyll
        run: touch "$DIST_DIR/.nojekyll"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.DIST_DIR }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
