name: Build and Deploy Frontend

on:
  push:
    branches: [dev, stage]
  pull_request:
    branches: [main, dev, stage]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging
        - development

env:
  NODE_VERSION: '18'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm run test:ci

      - name: Build for development
        if: github.ref == 'refs/heads/dev'
        run: npm run build
        env:
          API_URL: ${{ secrets.DEV_API_URL }}
          BACKEND_URL: ${{ secrets.DEV_BACKEND_URL }}
          FRONTEND_URL: ${{ secrets.DEV_FRONTEND_URL }}

      - name: Build for staging
        if: github.ref == 'refs/heads/stage'
        run: npm run build:prod
        env:
          API_URL: ${{ secrets.STAGE_API_URL }}
          BACKEND_URL: ${{ secrets.STAGE_BACKEND_URL }}
          FRONTEND_URL: ${{ secrets.STAGE_FRONTEND_URL }}

      - name: Build for production
        if: github.ref == 'refs/heads/main'
        run: npm run build:prod
        env:
          API_URL: ${{ secrets.PROD_API_URL }}
          BACKEND_URL: ${{ secrets.PROD_BACKEND_URL }}
          FRONTEND_URL: ${{ secrets.PROD_FRONTEND_URL }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist/

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy to GitHub Pages (Dev)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/demo
          destination_dir: dev
          keep_files: false

  deploy-stage:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/stage'
    
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy to GitHub Pages (Stage)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/demo
          destination_dir: stage
          keep_files: false

  deploy-prod:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'production'
    
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
          path: dist/

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy to AWS S3 (Production)
        run: |
          echo "🚀 Deploying to S3 bucket: ${{ secrets.PROD_S3_BUCKET }}"
          aws s3 sync dist/demo s3://${{ secrets.PROD_S3_BUCKET }} --delete --cache-control "public, max-age=31536000"
          aws s3 cp dist/demo/index.html s3://${{ secrets.PROD_S3_BUCKET }}/index.html --cache-control "no-cache, no-store, must-revalidate"
          echo "✅ Production deployment completed!"

      - name: Invalidate CloudFront Cache (Production)
        run: |
          echo "🔄 Invalidating CloudFront: ${{ secrets.PROD_CLOUDFRONT_ID }}"
          aws cloudfront create-invalidation --distribution-id ${{ secrets.PROD_CLOUDFRONT_ID }} --paths "/*"
          echo "✅ CloudFront cache invalidated!"
